import {CONFIG} from "./config.js";import {Header} from "./components/header.js";import {Filters} from "./components/filters.js";import {renderSidebar} from "./components/sidebar.js";import {createMap} from "./components/map.js";import {loadEvents} from "./providers/index.js";import {filterEvents} from "./services/events.js";import {geocode} from "./services/geocode.js";
const state={center:{...CONFIG.defaultCenter},radius:CONFIG.defaultRadiusMiles,zoom:CONFIG.defaultZoom,window:"today",category:"all",events:[]};
const root=document.querySelector("#app");root.innerHTML=`<div class="shell">${Header()}<div id="filters"></div><main class="main"><aside id="sidebar" class="sidebar"></aside><section class="map-wrap"><div id="map" class="map"></div><div class="map-overlay"><div class="radius-row"><strong>Radius</strong><input id="radius" type="range" min="1" max="${CONFIG.maxRadiusMiles}" value="${state.radius}"><span id="radiusLabel" class="radius-label">${state.radius} mi</span></div><div class="muted">Move map to reposition search center</div></div></section></main></div>`;
const mapUI=createMap(document.querySelector("#map"),state,(center,zoom)=>{state.center=center;state.zoom=zoom;render()});
function render(){document.querySelector("#filters").innerHTML=Filters(state);const visible=filterEvents(state.events,state);renderSidebar(document.querySelector("#sidebar"),visible,state);mapUI.setRadius(state.radius,state.center);mapUI.renderEvents(visible,selectEvent);bindFilters()}
function bindFilters(){document.querySelectorAll("[data-window]").forEach(b=>b.onclick=()=>{state.window=b.dataset.window;render()});document.querySelectorAll("[data-category]").forEach(b=>b.onclick=()=>{state.category=b.dataset.category;render()})}
function selectEvent(id){document.querySelectorAll(".card").forEach(c=>c.classList.toggle("selected",c.dataset.eventId===id));document.querySelector('[data-event-id="'+CSS.escape(id)+'"]')?.scrollIntoView({behavior:"smooth",block:"center"})}
document.querySelector("#radius").oninput=e=>{state.radius=Number(e.target.value);document.querySelector("#radiusLabel").textContent=state.radius+" mi";render()};
document.querySelector("#placeSearch").addEventListener("keydown",async e=>{if(e.key!=="Enter"||!e.target.value.trim())return;e.target.disabled=true;try{const p=await geocode(e.target.value.trim());if(p){state.center={lat:p.lat,lng:p.lng};mapUI.flyTo(state.center,11)}}finally{e.target.disabled=false}});
render();loadEvents().then(events=>{state.events=events;render()}).catch(console.error);